# Generated by Django 4.1 on 2023-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='campo1',
            field=models.IntegerField(max_length=150),
        ),
    ]
