# Generated by Django 4.1 on 2023-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_campo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='campo1',
        ),
        migrations.AddField(
            model_name='person',
            name='test',
            field=models.CharField(default=11, max_length=150),
            preserve_default=False,
        ),
    ]
