# Generated by Django 5.0 on 2023-12-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_person_campo1_person_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='test',
            new_name='numero_inscricao',
        ),
    ]
