# Generated by Django 5.0 on 2023-12-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_test_person_numero_inscricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='campo3',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='campo2',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='campo4',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='campo5',
            new_name='telefone',
        ),
    ]
